"""empty message

Revision ID: c0addd040ef9
Revises: 4009186601ea
Create Date: 2017-03-22 12:35:50.294259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0addd040ef9'
down_revision = '4009186601ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('background',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imgurl', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('background')
    # ### end Alembic commands ###
